// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyqzdptpujltjfdemedi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5cXpkcHRwdWpsdGpmZGVtZWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODQ5OTUsImV4cCI6MjA2NDk2MDk5NX0.xXYABucGkN9uc8BpqnsGopXjN5_D6BdrtuHd4WH6CzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);